# fly.toml app configuration file generated for tailscale-mysql2 on 2024-09-04T12:22:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tailscale-mysql2'
primary_region = 'lax'

[build]

[env]
  MYSQL_DATABASE = 'some_db'
  MYSQL_USER = 'non_root_user'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
